ALTER TABLE IF EXISTS checklist
    ADD COLUMN IF NOT EXISTS ativo BOOLEAN;

UPDATE checklist
SET ativo = TRUE
WHERE ativo IS NULL;

ALTER TABLE IF EXISTS checklist
    ALTER COLUMN ativo SET DEFAULT TRUE,
    ALTER COLUMN ativo SET NOT NULL;
